

CREATE TABLE YW_USER
(
     ID NUMERIC,
     NAME VARCHAR2(100)
);

INSERT INTO YW_USER(ID,NAME) VALUES(1,'ABC');
INSERT INTO YW_USER(ID,NAME) VALUES(2,'种种')

CREATE TABLE TEACHER (
   ID VARCHAR2(100) NOT NULL,
   NAME NVARCHAR2(200) NULL,
   CONSTRAINT PK_TEACHER_ID PRIMARY KEY(ID)
);
CREATE TABLE STUDENT (
   ID VARCHAR2(100) NOT NULL,
   NAME NVARCHAR2(200) NULL,
   ISMALE NUMBER(10,0) NULL,
   STUDENTNUMBER NUMBER(10,0) NULL,
    CONSTRAINT PK_STUDENT_ID PRIMARY KEY(ID)
);
CREATE TABLE STUDENT_TEACHER (
   STUDENTID VARCHAR2(100) NOT NULL,
   TEACHERID  VARCHAR2(100) NOT NULL
);

SELECT * FROM STUDENT;
SELECT * FROM TEACHER;
SELECT * FROM STUDENT_TEACHER;

DELETE FROM TEACHER;
DELETE FROM STUDENT;
DELETE FROM STUDENT_TEACHER;
COMMIT;


UPDATE STUDENT SET NAME=@NAME WHERE ID=@ID

DROP TABLE TEACHER;
DROP TABLE STUDENT;
DROP TABLE STUDENT_TEACHER;



CREATE TABLE T_PERSON (
   ID        NUMBER(10,0) NOT NULL,
   NAME      VARCHAR2(200) NULL,
   AGE        NUMBER(10,0) NULL,
   NATIONALITYID NUMBER(10,0) NULL
);

CREATE TABLE T_NATIONALITY (
   ID        NUMBER(10,0) NOT NULL,
   NAME      VARCHAR2(200) NULL
);

SELECT * FROM T_PERSON;
SELECT * FROM T_NATIONALITY;

DELETE FROM T_PERSON;
DELETE FROM T_NATIONALITY;
COMMIT;

INSERT INTO T_PERSON(ID,NAME,AGE,NATIONALITYID) VALUES(1,'徐齐',86,1);
INSERT INTO T_PERSON(ID,NAME,AGE,NATIONALITYID) VALUES(2,'穗',86,2);
INSERT INTO T_NATIONALITY(ID,NAME) VALUES(1,'中国');
INSERT INTO T_NATIONALITY(ID,NAME) VALUES(2,'美国');
COMMIT;



CREATE TABLE T_FACE (
   ID        NUMBER(10,0) NOT NULL,
   NAME      VARCHAR2(200) NULL,
   TYPEID    NUMBER(10,0)
);
CREATE TABLE T_FACETYPE (
   ID        NUMBER(10,0) NOT NULL,
   NAME      VARCHAR2(200) NULL
);
CREATE TABLE T_PHOTO (
   FACEID    NUMBER(10,0) NOT NULL,
   PATH      VARCHAR2(200) NULL
);


SELECT * FROM T_FACE;
SELECT * FROM T_FACETYPE;
SELECT * FROM T_PHOTO;

DELETE FROM T_FACE;
DELETE FROM T_FACETYPE;
DELETE FROM T_PHOTO;
COMMIT;

UPDATE T_FACE SET NAME='BBB' WHERE ID=1;

insert into T_face(id,name ) values(1,'33');

